theme: jekyll-theme-minimal
title: A good CDK inhibitor, a good inhibition of cell proliferation
description: What makes a good inhibitor against cell proliferation?
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
